spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1/dots_test
      database: dots_test
  mongodb:
    embedded:
      version: 5.0.6 # latest version supported on Windows :{
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: fake-client-id
            clientSecret: fake-client-secret
          google:
            clientId: fake-client-id
            clientSecret: fake-client-secret
