# Global YML configuration goes here.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dots_timeservice
    #username: ...
    #password: ...
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
