spring:
  datasource:
    # TODO: replace with embedded DB!
    url: jdbc:postgresql://localhost:5432/dots_turnservice_test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
dots:
  service_to_service_secret: (not used)