# Global YML configuration goes here.
spring:
  datasource:
    ## default connection pool: use Hikari.
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/dots_turnservice?autoreconnect=true
    #username: ...
    #password: ...
  flyway:
    url: jdbc:postgresql://localhost:5432/dots_turnservice
    validateMigrationNaming: true
    #user: ...
    #password: ...
  jpa:
    hibernate:
#      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          # Store dates in UTC when we persist them
          time_zone: UTC
    show-sql: true
server:
  port:
    8081
dots:
  tickCron: 0 0 0 * * * # every day at midnight