name: JEE CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: |
          chmod +x ./services/web/gradlew
          chmod +x ./services/turnservice/gradlew
          chmod +x ./services/playerservice/gradlew
          chmod +x ./services/encounterservice/gradlew

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Build and run web with tests
        run: |
          cd services/web
          ./gradlew clean test
      - name: Build and run turn service with tests
        run: |
          cd services/turnservice
          ./gradlew clean test
      - name: Build and run player service with tests
        run: |
          cd services/playerservice
          ./gradlew clean test
      - name: Build and run encounter service with tests
        run: |
          cd services/encounterservice
          ./gradlew clean test
        