name: JEE CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./services/web/gradlew
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle        
      - name: Build and run tests
        run: |
          cd services/web
          ./gradlew clean test
  turn-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./services/turnservice/gradlew
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle        
      - name: Build and run tests
        run: |
          cd services/turnservice
          ./gradlew clean test
  player-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./services/playerservice/gradlew
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle        
      - name: Build and run tests
        run: |
          cd services/playerservice
            ./gradlew clean test
  encounter-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./services/encounterservice/gradlew
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle        
      - name: Build and run tests
        run: |
          cd services/encounterservice
          ./gradlew clean test